### PR TITLE
specific name to store downloaded file

### PR DESCRIPTION
**Pull request by hordesalik**
Allow to specify the name of the file/files to be downloaded. Useful when url doesn't represent file name in url, but only file id. E.g. url https://host.com/download/123, browsers understand Content-Disposition header with file name, but this plugin doesn't.

### CODE REVIEW

**Review by mramonlopez — COMMENTED** [review]
Hi,

I'm back from vacation. Please, let me check your commit tomorrow before approve it. Thanks.

**Comment by hordesalik** [comment]
HI @mramonlopez 
How is the matter going?

**Comment by hordesalik** [comment]
Will you push a new version with this change?

**Comment by mramonlopez** [comment]
Done!

**Pull request merged**
